version: "3.8"
x-logging: &lokilogs
  logging:
    driver: loki
    options:
      loki-url: "http://192.168.0.40:3100/loki/api/v1/push"

services:
  web:
    image: sreeramb93/demo-server:${GITCOMMIT}
    build:
      context: ./server
      dockerfile: Dockerfile
      labels:
        - SERVICE_80_CHECK_HTTP=/ready-check
        - SERVICE_80_CHECK_INTERVAL=15s
        - SERVICE_80_CHECK_TIMEOUT=1s
        - SERVICE_80_TAGS=demo-server
        - SERVICE_80_NAME=demo
      args:
        - "GITCOMMIT=${GITCOMMIT}"
    networks:
      - overlay
    volumes:
      - ./server:/app # modified here to take into account the new app path
  consul-server:
    image: consul:1.9.5
    volumes:
      - ./consul/server_config.json:/consul/config/server.json:ro
      - ./consul/certs/:/consul/config/certs/:ro
      - consul_data:/consul/data
    networks:
      overlay:
        ipv4_address: ${CONSUL_SERVER_IP}
    ports:
      - '8500:8500'
      - '8600:8600/tcp'
      - '8600:8600/udp'
    command: 'agent -server -ui -client=0.0.0.0 -bootstrap-expect=1'
  registrator:
    container_name: registrator
    image: gliderlabs/registrator:master
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    command: -internal consul://consul-server:8500
    restart: always
    networks:
      - overlay
    links:
      - consul-server
    depends_on:
      - consul-server
  haproxy:
    image: sreeramb93/ha-proxy:2.4
    build:
      context: ./haproxy
      dockerfile: Dockerfile
    networks:
      overlay:
        ipv4_address: ${HA_PROXY_IP}
    ports:
      - "8081:8081"
      - "9999:9999"
      - "8404:8404"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - web
      - consul-server
    links:
      - consul-server

volumes:
  consul_data: {}

networks:
  overlay:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}
