global:
  scrape_interval: 5s
  evaluation_interval: 5s
  scrape_timeout: 1s

rule_files:
- '/etc/prometeus/alert.rules'
alerting:
  alertmanagers:
  - static_configs:
    - targets:
        - alertmanager:9093
    # whatever you want
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']
      labels:
        alias: 'prometheus'
  - job_name: 'haproxy'
    static_configs:
    - targets: ['192.168.0.33:8404']
      labels:
        alias: 'haproxy'
  - job_name: 'cadvisor'
    static_configs:
    - targets: ['cadvisor:8080']
      labels:
        alias: 'cadvisor'
