groups:
- name: Haproxy Instance Check
  rules:
    - alert: low_instances
      expr: haproxy_backend_active_servers{proxy="webservers"} < 2
      for: 10s
      labels:
        severity: critical
        alertvalue: "{{ $value }}"
      annotations:
        summary: "Low number of backend instances"
        description: "Low number of webservers detected, please adjust ratelimits"
    - alert: high_instances
      expr: haproxy_backend_active_servers{proxy="webservers"} >= 4
      for: 10s
      labels:
        severity: warning
        alertvalue: "{{ $value }}"
      annotations:
        summary: "High number of backend webservers"
        description: "High number of webservers detected, please adjust ratelimits"
    - alert: optimal_instances
      expr: haproxy_backend_active_servers{proxy="webservers"} >= 2 and haproxy_backend_active_servers{proxy="webservers"} < 4
      for: 10s
      labels:
        severity: critical
        alertvalue: "{{ $value }}"
      annotations:
        summary: "Optimal number of backend web servers"
        description: "Optimal number of webservers detected, Please adjust rate limits"
