version: "3.8"
services:
  prometheus:
    image: 'prom/prometheus:latest'
    networks:
      - overlay
      - mape-k
    ports:
      - '9090:9090'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
        #      - '--storage.tsdb.path=/data'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        #      - prometheus_data:/data
    links:
      - cadvisor
  alertmanager:
      image: prom/alertmanager
      volumes:
        - ./prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml
          #- alertmanager_data:/data
      networks:
        - mape-k
      command:
        - '--config.file=/etc/alertmanager/alertmanager.yml'
          #- '--storage.path=/data'
      ports:
        - '9093:9093'
  promtail:
    image: 'grafana/promtail:latest'
    networks:
      - overlay
      - mape-k
    ports:
      - '9080:9080'
    command: -config.file=/etc/promtail/promtail.yml
    volumes:
      - /var/log:/var/log
      - ./loki/promtail_config.yml:/etc/promtail/promtail.yml
  loki:
    image: 'grafana/loki:latest'
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/loki.yml
    volumes:
      - ./loki/loki_config.yml:/etc/loki/loki.yml
    networks:
      mape-k:
      overlay:
          ipv4_address: ${LOKI_SERVER_IP}
    depends_on:
      - promtail
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - loki
      - promtail
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    networks:
      - mape-k
  cadvisor:
    image: 'google/cadvisor:latest'
    container_name: cadvisor
    ports:
      - '8080:9095'
    networks:
      - overlay
      - mape-k
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk:/dev/disk/:ro
  adaptation:
    image: sreeramb93/adaptation-server:${GITCOMMIT}
    build:
      context: ./adaptation
      dockerfile: Dockerfile
      args:
        - "GITCOMMIT=${GITCOMMIT}"
    environment:
      ADAPTATION_DB_HOST: adaptation_db
      ADAPTATION_DB_PORT: 3309
      DEBUG_TRUE: "TRUE"
    networks:
      - mape-k
    ports:
      - '8091:80'
    volumes:
      - ./adaptation:/app
      - ./adaptation/static:/app/static
      - adb_logs_data:/var/logs
    depends_on:
      - adaptation_db
    links:
      - adaptation_db
  adaptation_db:
    image: mysql
    networks:
      - mape-k
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: adaptation
      MYSQL_USER: sreeram
      MYSQL_PASSWORD: adelaide7093
      MYSQL_TCP_PORT: 3309
    volumes:
      - adb_data:/var/lib/mysql/

volumes:
  prometheus_data: {}
  alertmanager_data: {}
  grafana_data: {}
  badger_data: {}
  adb_data: {}
  adb_logs_data: {}

networks:
  mape-k:
    driver: bridge
  overlay:
    external:
      name: demo-server_overlay
